Ahoo-Wang/CosId

.github/workflows/integration-test.yml
cosid-jdbc/src/main/init-script/init-cosid-mysql.sql

- https://github.com/actions/virtual-environments/issues/375
- https://github.blog/changelog/2020-02-21-github-actions-breaking-change-ubuntu-virtual-environments-will-no-longer-start-the-mysql-service-automatically/

Fix CosId-Jdbc integration test

---

cosid-example/src/main/resources/application.yaml

fix demo not runnable by correct application.yaml

fix demo not runnable by correct application.yaml

---

cosid-example/src/main/resources/application.yaml
cosid-shardingsphere/src/main/java/me/ahoo/cosid/shardingsphere/sharding/utils/PropertiesUtil.java

ignore type check while read integer field.

ignore type check while read integer field.

---

cosid-benchmark/build.gradle.kts

Fixes #ISSUSE_ID.
- upgrade to CosId-v1.8.9 for benchmark
-
-

upgrade to CosId-v1.8.9 for benchmark

---

cosid-spring-boot-starter/src/main/java/me/ahoo/cosid/spring/boot/starter/snowflake/SnowflakeIdProperties.java

make machineId guarder enabled default true

make machineId guarder enabled default true

---

config/checkstyle/checkstyle.xml
cosid-core/src/main/java/me/ahoo/cosid/uncertainty/OriginalIdOverflowException.java
cosid-core/src/main/java/me/ahoo/cosid/uncertainty/UncertaintyIdGenerator.java
cosid-core/src/test/java/me/ahoo/cosid/uncertainty/UncertaintyIdGeneratorTest.java
gradle.properties

- add `UncertaintyIdGenerator`

add `UncertaintyIdGenerator`

---

.github/workflows/integration-test.yml
README.md
build.gradle.kts
codecov.yml
cosid-benchmark/build.gradle.kts
cosid-dependencies/build.gradle.kts
cosid-proxy/build.gradle.kts
cosid-proxy/src/test/java/me/ahoo/cosid/proxy/ProxyIdSegmentDistributorTest.java
cosid-proxy/src/test/java/me/ahoo/cosid/proxy/ProxyMachineIdDistributorTest.java
cosid-proxy/src/test/java/me/ahoo/cosid/proxy/ProxyServerLauncher.java
settings.gradle.kts

* Support CI for CosId-Proxy
* Update dependency `Spring Boot` to `v2.6.9`
* Update dependency `Spring Cloud` to `2021.0.3`
* Update dependency `spotbugs-gradle-plugin` to `5.0.9`

 Support CI for CosId-Proxy

---

build.gradle.kts
cosid-dependencies/build.gradle.kts
cosid-mybatis/src/main/java/me/ahoo/cosid/mybatis/CosIdPlugin.java
cosid-mybatis/src/test/java/me/ahoo/cosid/mybatis/CosIdPluginTest.java
cosid-proxy-server/build.gradle.kts
cosid-shardingsphere/build.gradle.kts
cosid-spring-boot-starter/build.gradle.kts
examples/cosid-example-jdbc/build.gradle.kts
examples/cosid-example-proxy/build.gradle.kts
examples/cosid-example-redis-cosid/build.gradle.kts
examples/cosid-example-redis/build.gradle.kts
examples/cosid-example-shardingsphere/build.gradle.kts
examples/cosid-example-zookeeper/build.gradle.kts
examples/cosid-example/build.gradle.kts
gradle.properties

Fixes #168 .
- Optimize Dependency management
- Fix issues(https://github.com/Ahoo-Wang/CosId/issues/168) caused by `MapperMethod.ParamMap.get` constraints

Dependency management

---

build.gradle.kts
config/logback-jmh.xml
config/logback.xml
cosid-core/src/main/java/me/ahoo/cosid/machine/InMemoryMachineStateStorage.java
gradle.properties

- refactor log level for `InMemoryMachineStateStorage`

refactor log level for `InMemoryMachineStateStorage`

---

build.gradle.kts
config/logback-jmh.xml
config/logback.xml
cosid-core/src/main/java/me/ahoo/cosid/machine/InMemoryMachineStateStorage.java
cosid-core/src/test/java/me/ahoo/cosid/machine/DefaultClockBackwardsSynchronizerTest.java
cosid-core/src/test/java/me/ahoo/cosid/machine/MachineIdGuarderTest.java
gradle.properties

Improve code coverage

---

cosid-mongo/src/main/java/me/ahoo/cosid/mongo/IdSegmentInitializer.java
cosid-mongo/src/main/java/me/ahoo/cosid/mongo/reactive/MongoReactiveCosIdSegmentCollection.java
cosid-mongo/src/main/java/me/ahoo/cosid/mongo/reactive/MongoReactiveIdSegmentDistributorFactory.java
cosid-mongo/src/main/java/me/ahoo/cosid/mongo/reactive/MongoReactiveIdSegmentInitializer.java
cosid-mongo/src/test/java/me/ahoo/cosid/mongo/MongoReactiveIdSegmentDistributorTest.java
gradle.properties

- Feature: support  `MongoReactiveCosIdSegmentCollection`

Feature: support  `MongoReactiveCosIdSegmentCollection`

---

cosid-spring-boot-starter/build.gradle.kts
cosid-spring-boot-starter/src/test/java/me/ahoo/cosid/spring/boot/starter/mongo/MongoLauncher.java
cosid-spring-boot-starter/src/test/java/me/ahoo/cosid/spring/boot/starter/segment/CosIdMongoSegmentAutoConfigurationTest.java
cosid-spring-boot-starter/src/test/java/me/ahoo/cosid/spring/boot/starter/segment/CosIdReactiveMongoSegmentAutoConfigurationTest.java

fix CI for MongoLauncher

---

cosid-core/src/main/java/me/ahoo/cosid/machine/MachineIdDistributor.java
cosid-jdbc/src/main/java/me/ahoo/cosid/jdbc/JdbcMachineIdDistributor.java
cosid-mongo/src/main/java/me/ahoo/cosid/mongo/CosIdMachineCollection.java
cosid-mongo/src/main/java/me/ahoo/cosid/mongo/Documents.java
cosid-mongo/src/main/java/me/ahoo/cosid/mongo/IdSegmentCollection.java
cosid-mongo/src/main/java/me/ahoo/cosid/mongo/MachineCollection.java
cosid-mongo/src/main/java/me/ahoo/cosid/mongo/MachineInitializer.java
cosid-mongo/src/main/java/me/ahoo/cosid/mongo/MongoCosIdSegmentCollection.java
cosid-mongo/src/main/java/me/ahoo/cosid/mongo/MongoIdSegmentCollection.java
cosid-mongo/src/main/java/me/ahoo/cosid/mongo/MongoIdSegmentDistributor.java
cosid-mongo/src/main/java/me/ahoo/cosid/mongo/MongoIdSegmentDistributorFactory.java
cosid-mongo/src/main/java/me/ahoo/cosid/mongo/MongoIdSegmentInitializer.java
cosid-mongo/src/main/java/me/ahoo/cosid/mongo/MongoMachineCollection.java
cosid-mongo/src/main/java/me/ahoo/cosid/mongo/MongoMachineIdDistributor.java
cosid-mongo/src/main/java/me/ahoo/cosid/mongo/MongoMachineInitializer.java
cosid-mongo/src/main/java/me/ahoo/cosid/mongo/reactive/BlockingAdapter.java
cosid-mongo/src/main/java/me/ahoo/cosid/mongo/reactive/MongoReactiveCosIdSegmentCollection.java
cosid-mongo/src/main/java/me/ahoo/cosid/mongo/reactive/MongoReactiveIdSegmentCollection.java
cosid-mongo/src/main/java/me/ahoo/cosid/mongo/reactive/MongoReactiveIdSegmentDistributorFactory.java
cosid-mongo/src/main/java/me/ahoo/cosid/mongo/reactive/MongoReactiveMachineCollection.java
cosid-mongo/src/main/java/me/ahoo/cosid/mongo/reactive/MongoReactiveMachineInitializer.java
cosid-mongo/src/test/java/me/ahoo/cosid/mongo/MongoIdSegmentInitializerTest.java
cosid-mongo/src/test/java/me/ahoo/cosid/mongo/MongoMachineIdDistributorTest.java
cosid-mongo/src/test/java/me/ahoo/cosid/mongo/MongoReactiveMachineIdDistributorTest.java
gradle.properties

Fixes #112 .
- Feature: support `MongoMachineIdDistributor`

Feature: support `MongoMachineIdDistributor`

---

cosid-spring-boot-starter/src/main/java/me/ahoo/cosid/spring/boot/starter/machine/CosIdMongoMachineIdDistributorAutoConfiguration.java
cosid-spring-boot-starter/src/main/java/me/ahoo/cosid/spring/boot/starter/machine/MachineProperties.java
cosid-spring-boot-starter/src/main/java/me/ahoo/cosid/spring/boot/starter/segment/CosIdMongoSegmentAutoConfiguration.java
cosid-spring-boot-starter/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
cosid-spring-boot-starter/src/test/java/me/ahoo/cosid/spring/boot/starter/machine/CosIdMongoMachineIdDistributorAutoConfigurationTest.java
cosid-spring-boot-starter/src/test/java/me/ahoo/cosid/spring/boot/starter/machine/CosIdReactiveMongoMachineIdDistributorAutoConfigurationTest.java
cosid-spring-boot-starter/src/test/java/me/ahoo/cosid/spring/boot/starter/segment/CosIdReactiveMongoSegmentAutoConfigurationTest.java

- Feature: support `CosIdMongoMachineIdDistributorAutoConfiguration`

Feature: support `CosIdMongoMachineIdDistributorAutoConfiguration`

---

cosid-mongo/src/test/java/me/ahoo/cosid/mongo/MongoMachineIdDistributorTest.java
cosid-mongo/src/test/java/me/ahoo/cosid/mongo/MongoReactiveMachineIdDistributorTest.java
cosid-test/src/main/java/me/ahoo/cosid/test/machine/distributor/Distribute.java
cosid-test/src/main/java/me/ahoo/cosid/test/machine/distributor/DistributeConcurrent.java
cosid-test/src/main/java/me/ahoo/cosid/test/machine/distributor/DistributeIdempotent.java
cosid-test/src/main/java/me/ahoo/cosid/test/machine/distributor/DistributeOverflow.java
cosid-test/src/main/java/me/ahoo/cosid/test/machine/distributor/DistributeRevert.java
cosid-test/src/main/java/me/ahoo/cosid/test/machine/distributor/DistributeSafeGuard.java
cosid-test/src/main/java/me/ahoo/cosid/test/machine/distributor/DistributeStable.java
cosid-test/src/main/java/me/ahoo/cosid/test/machine/distributor/Guard.java
cosid-test/src/main/java/me/ahoo/cosid/test/machine/distributor/GuardLost.java
cosid-test/src/main/java/me/ahoo/cosid/test/machine/distributor/MachineIdDistributorSpec.java
cosid-test/src/main/java/me/ahoo/cosid/test/machine/distributor/Revert.java

- Refactor: Improve unit test stability in CI

Refactor: Improve unit test stability in CI

---

cosid-core/src/main/java/me/ahoo/cosid/converter/ToStringIdConverter.java
cosid-core/src/test/java/me/ahoo/cosid/converter/ToStringIdConverterTest.java
cosid-spring-boot-starter/src/main/java/me/ahoo/cosid/spring/boot/starter/IdConverterDefinition.java
cosid-spring-boot-starter/src/main/java/me/ahoo/cosid/spring/boot/starter/segment/CosIdSegmentAutoConfiguration.java
cosid-spring-boot-starter/src/main/java/me/ahoo/cosid/spring/boot/starter/snowflake/CosIdSnowflakeAutoConfiguration.java
cosid-spring-boot-starter/src/test/java/me/ahoo/cosid/spring/boot/starter/IdConverterDefinitionTest.java
cosid-spring-boot-starter/src/test/java/me/ahoo/cosid/spring/boot/starter/segment/CosIdSegmentAutoConfigurationTest.java
cosid-spring-boot-starter/src/test/java/me/ahoo/cosid/spring/boot/starter/snowflake/CosIdSnowflakeAutoConfigurationTest.java
document/docs/config/README.md
examples/cosid-example-redis/src/main/resources/application.yaml
gradle.properties

- support PadStartIdConverter for `ToString`. #285

support PadStartIdConverter for `ToString`. #285

---

cosid-core/src/main/java/me/ahoo/cosid/machine/DefaultMachineIdGuarder.java
cosid-core/src/test/java/me/ahoo/cosid/machine/DefaultMachineIdGuarderTest.java
cosid-spring-boot-starter/src/main/java/me/ahoo/cosid/spring/boot/starter/cosid/CosIdGeneratorAutoConfiguration.java
cosid-spring-boot-starter/src/test/java/me/ahoo/cosid/spring/boot/starter/cosid/CosIdGeneratorAutoConfigurationTest.java
gradle.properties

- fix: register null to `DefaultMachineIdGuarder`

fix: register null to `DefaultMachineIdGuarder`

---

README.md

Update README.md 中关于SnowflakeId，timestamp的计算文案

---

cosid-mongo/src/main/java/me/ahoo/cosid/mongo/reactive/BlockingAdapter.java
gradle.properties

refactor: `BlockingAdapter`

---

cosid-core/src/main/java/me/ahoo/cosid/segment/grouped/DateGroupedSupplier.java
cosid-core/src/main/java/me/ahoo/cosid/segment/grouped/DefaultGroupedIdSegmentDistributor.java
cosid-core/src/main/java/me/ahoo/cosid/segment/grouped/GroupedIdSegmentDistributor.java
cosid-core/src/main/java/me/ahoo/cosid/segment/grouped/GroupedIdSegmentDistributorFactory.java
cosid-core/src/main/java/me/ahoo/cosid/segment/grouped/GroupedKey.java
cosid-core/src/main/java/me/ahoo/cosid/segment/grouped/GroupedSupplier.java
cosid-core/src/test/java/me/ahoo/cosid/segment/grouped/DateGroupedSupplierTest.java
cosid-core/src/test/java/me/ahoo/cosid/segment/grouped/DefaultGroupedIdSegmentDistributorTest.java
cosid-jdbc/src/test/java/me/ahoo/cosid/jdbc/GroupedJdbcIdSegmentDistributorTest.java
cosid-mongo/src/test/java/me/ahoo/cosid/mongo/GroupedMongoReactiveIdSegmentDistributorTest.java
cosid-spring-redis/src/test/java/me/ahoo/cosid/spring/redis/GroupedSpringRedisIdSegmentDistributorTest.java
cosid-test/src/main/java/me/ahoo/cosid/test/segment/distributor/GroupedIdSegmentDistributorSpec.java
cosid-test/src/main/java/me/ahoo/cosid/test/segment/distributor/IdSegmentDistributorSpec.java
gradle.properties

- feat: Support `GroupedIdSegmentDistributor`.

feat: Support `GroupedIdSegmentDistributor`.

---

cosid-core/src/main/java/me/ahoo/cosid/machine/HostAddressSupplier.java
cosid-core/src/main/java/me/ahoo/cosid/machine/LocalHostAddressSupplier.java
cosid-core/src/test/java/me/ahoo/cosid/machine/LocalHostAddressSupplierTest.java
cosid-spring-boot-starter/build.gradle.kts
cosid-spring-boot-starter/src/main/java/me/ahoo/cosid/spring/boot/starter/machine/CosIdHostNameAutoConfiguration.java
cosid-spring-boot-starter/src/main/java/me/ahoo/cosid/spring/boot/starter/machine/CosIdMachineAutoConfiguration.java
cosid-spring-boot-starter/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
cosid-spring-boot-starter/src/test/java/me/ahoo/cosid/spring/boot/starter/cosid/CosIdGeneratorAutoConfigurationTest.java
cosid-spring-boot-starter/src/test/java/me/ahoo/cosid/spring/boot/starter/machine/CosIdHostNameAutoConfigurationTest.java
cosid-spring-boot-starter/src/test/java/me/ahoo/cosid/spring/boot/starter/machine/CosIdJdbcMachineIdDistributorAutoConfigurationTest.java
cosid-spring-boot-starter/src/test/java/me/ahoo/cosid/spring/boot/starter/machine/CosIdMachineAutoConfigurationTest.java
cosid-spring-boot-starter/src/test/java/me/ahoo/cosid/spring/boot/starter/machine/CosIdMongoMachineIdDistributorAutoConfigurationTest.java
cosid-spring-boot-starter/src/test/java/me/ahoo/cosid/spring/boot/starter/machine/CosIdSpringRedisMachineIdDistributorAutoConfigurationTest.java
cosid-spring-boot-starter/src/test/java/me/ahoo/cosid/spring/boot/starter/machine/CosIdZookeeperMachineIdDistributorAutoConfigurationTest.java
cosid-spring-boot-starter/src/test/java/me/ahoo/cosid/spring/boot/starter/snowflake/CosIdSnowflakeAutoConfigurationTest.java
examples/cosid-example-redis/build.gradle.kts
gradle.properties

- feat: support `HostAddressSupplier`
- feat: change `org.springframework.cloud:spring-cloud-commons` dependency to optional

feat: support `HostAddressSupplier`

---

cosid-core/src/test/java/me/ahoo/cosid/accessor/NotFoundCosIdAccessorTest.java
cosid-core/src/test/java/me/ahoo/cosid/accessor/registry/DefaultAccessorRegistryTest.java
cosid-core/src/test/java/me/ahoo/cosid/accessor/scanner/DefaultCosIdScannerTest.java
cosid-core/src/test/java/me/ahoo/cosid/annotation/entity/IntIdEntity.java
cosid-dependencies/build.gradle.kts
cosid-proxy-server/build.gradle.kts
cosid-proxy-server/src/dist/config/application.yaml
cosid-proxy-server/src/main/java/me/ahoo/cosid/proxy/server/configuration/SwaggerConfiguration.java
cosid-proxy-server/src/main/java/me/ahoo/cosid/proxy/server/controller/IdController.java
cosid-proxy-server/src/main/java/me/ahoo/cosid/proxy/server/controller/MachineController.java
cosid-proxy-server/src/main/java/me/ahoo/cosid/proxy/server/controller/SegmentController.java
cosid-proxy-server/src/main/java/me/ahoo/cosid/proxy/server/error/ErrorResponse.java
cosid-proxy-server/src/main/java/me/ahoo/cosid/proxy/server/error/GlobalRestExceptionHandler.java
cosid-proxy-server/src/main/resources/application.yaml
cosid-proxy/src/main/java/me/ahoo/cosid/proxy/ErrorResponse.java
cosid-proxy/src/main/java/me/ahoo/cosid/proxy/ProxyIdSegmentDistributor.java
cosid-proxy/src/main/java/me/ahoo/cosid/proxy/ProxyIdSegmentDistributorFactory.java
cosid-proxy/src/main/java/me/ahoo/cosid/proxy/ProxyMachineIdDistributor.java
cosid-proxy/src/test/java/me/ahoo/cosid/proxy/JsonsTest.java
cosid-proxy/src/test/java/me/ahoo/cosid/proxy/ProxyMachineIdDistributorTest.java
cosid-proxy/src/test/java/me/ahoo/cosid/proxy/ProxyServerLauncher.java
cosid-test/src/main/java/me/ahoo/cosid/test/machine/distributor/MachineIdDistributorSpec.java
gradle.properties
gradle/libs.versions.toml

feat: Enhance OpenAPI for cosid-proxy

---

.github/workflows/codecov.yml
.github/workflows/integration-test.yml
cosid-core/src/main/java/me/ahoo/cosid/accessor/parser/CompositeFieldDefinitionParser.java
cosid-core/src/test/java/me/ahoo/cosid/accessor/parser/CompositeFieldDefinitionParserTest.java
cosid-core/src/test/java/me/ahoo/cosid/annotation/entity/IdNotFoundEntity.java
cosid-core/src/test/java/me/ahoo/cosid/snowflake/MillisecondSnowflakeIdTest.java
cosid-spring-boot-starter/build.gradle.kts
cosid-spring-boot-starter/src/main/java/me/ahoo/cosid/spring/boot/starter/CosIdAutoConfiguration.java
cosid-spring-boot-starter/src/main/java/me/ahoo/cosid/spring/boot/starter/jdbc/CosIdJdbcAutoConfiguration.java
cosid-spring-boot-starter/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
cosid-spring-boot-starter/src/test/java/me/ahoo/cosid/spring/boot/starter/CosIdAutoConfigurationTest.java
cosid-spring-boot-starter/src/test/java/me/ahoo/cosid/spring/boot/starter/jdbc/CosIdJdbcAutoConfigurationTest.java
cosid-spring-data-jdbc/build.gradle.kts
cosid-spring-data-jdbc/src/main/java/me/ahoo/cosid/spring/data/jdbc/CosIdBeforeConvertCallback.java
cosid-spring-data-jdbc/src/main/java/me/ahoo/cosid/spring/data/jdbc/IdAnnotationDefinitionParser.java
cosid-spring-data-jdbc/src/test/java/me/ahoo/cosid/spring/data/jdbc/CosIdBeforeConvertCallbackTest.java
gradle.properties
settings.gradle.kts

fix #107
``` java
static class IdEntity {
@Id
private long id;
public long getId() {
return id;
}
public IdEntity setId(int id) {
this.id = id;
return this;
}
}
static class CosIdEntity {
@CosId
private long id;
public long getId() {
return id;
}
public CosIdEntity setId(int id) {
this.id = id;
return this;
}
}
```

feat: support `spring-data-jdbc`

---

cosid-test/src/main/java/me/ahoo/cosid/test/ConcurrentGenerateStingSpec.java

format code

---

cosid-core/src/main/java/me/ahoo/cosid/cosid/FriendlyCosIdGenerator.java
cosid-core/src/main/java/me/ahoo/cosid/cosid/FriendlyIdStateParser.java
cosid-core/src/test/java/me/ahoo/cosid/cosid/FriendlyCosIdGeneratorTest.java
cosid-spring-boot-starter/src/main/java/me/ahoo/cosid/spring/boot/starter/cosid/CosIdGeneratorAutoConfiguration.java
cosid-spring-boot-starter/src/main/java/me/ahoo/cosid/spring/boot/starter/cosid/CosIdGeneratorProperties.java
cosid-spring-boot-starter/src/test/java/me/ahoo/cosid/spring/boot/starter/cosid/CosIdGeneratorPropertiesTest.java
documentation/docs/reference/config/cosid-generator.md

- Implement FriendlyCosIdGenerator and FriendlyIdStateParser
- Update CosIdGeneratorProperties to include new friendly ID options
- Add tests for friendly ID generator functionality
- Update documentation to reflect new friendly ID generator type

feat(cosid): add friendly ID generator support

---

cosid-core/src/main/java/me/ahoo/cosid/converter/SnowflakeFriendlyIdConverter.java
cosid-core/src/main/java/me/ahoo/cosid/snowflake/SnowflakeIdStateParser.java
cosid-core/src/main/java/me/ahoo/cosid/stat/converter/SnowflakeFriendlyIdConverterStat.java
cosid-core/src/test/java/me/ahoo/cosid/converter/SnowflakeFriendlyIdConverterTest.java
documentation/docs/guide/specific-id.md
examples/cosid-example-redis/src/main/resources/application.yaml

- Implement SnowflakeFriendlyIdConverterStat to provide detailed statistics
- Enhance SnowflakeIdStateParser with new methods for padStart and character size
- Update SnowflakeFriendlyIdConverter to support padStart configuration
- Add new configuration example for orderly snowflake friendly ID
- Modify existing tests to use new SnowflakeFriendlyIdConverterStat

feat(core): add support for orderly snowflake friendly ID conversion

---

documentation/docs/reference/config/basic.md
documentation/docs/reference/config/cosid-generator.md
documentation/docs/reference/config/snowflake.md

- Add new Friendly converter configuration options
- Update CosIdGeneratorProperties to include FRIENDLY type
- Remove friendly property from Snowflake configuration

docs(config): update ID converter and generator configuration documentation

---

cosid-core/src/main/java/me/ahoo/cosid/annotation/AnnotationDefinitionParser.java

- Streamline the logic for parsing CosId annotations
- Improve readability and reduce redundancy in the parse method
- Enhance performance by minimizing annotation lookups

refactor(cosid-core): optimize annotation definition parsing logic

---

cosid-core/src/main/java/me/ahoo/cosid/machine/DefaultClockBackwardsSynchronizer.java
cosid-core/src/test/java/me/ahoo/cosid/machine/DefaultClockBackwardsSynchronizerTest.java

- Add Thread.onSpinWait() to improve CPU usage during clock synchronization
- This change helps reduce CPU contention in multi-threaded environments

perf(cosid-core): add spin wait hint for clock sync

---

cosid-spring-boot-starter/src/main/java/me/ahoo/cosid/spring/boot/starter/actuate/CosIdEndpointAutoConfiguration.java
cosid-spring-boot-starter/src/test/java/me/ahoo/cosid/spring/boot/starter/CosIdAutoConfigurationTest.java
cosid-spring-boot-starter/src/test/java/me/ahoo/cosid/spring/boot/starter/actuate/CosIdEndpointAutoConfigurationTest.java

- Add test case for CosIdAutoConfiguration when disabled
- Add test case for CosIdEndpointAutoConfiguration when disabled
- Apply ConditionalOnCosIdEnabled to CosIdEndpointAutoConfiguration

fix(spring-boot): Apply ConditionalOnCosIdEnabled to CosIdEndpointAutoConfiguration

---

documentation/docs/guide/specific-id.md

- Reorganize SnowflakeId-related configurations under a single section
- Reorganize SegmentId-related configurations under a single section
- Update heading levels for better readability and consistency

docs(guide): update specific ID documentation structure

---

README.md
README.zh-CN.md

- Add DeepWiki badge to both README.md and README.zh-CN.md
- The badge provides a link for asking questions on DeepWiki

docs: add DeepWiki badge to README files

---

gradle.properties
gradle/libs.versions.toml

- Upgrade coapi from 1.11.5 to 1.12.0 in gradle/libs.versions.toml

build(deps): update coapi version to 1.12.0
